package com.icthh.xm.commons.lep.groovy;

import lombok.extern.slf4j.Slf4j;
import org.codehaus.groovy.ast.ClassNode;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Drops the {@code @NamedParams} nodes groovy accumulates on the static {@code ClassNode}s it reuses
 * for every constructor generated by {@code @MapConstructor}.
 *
 * <p>{@code MapConstructorASTTransformation} holds a JVM-wide {@code MAP_TYPE} node and uses it as the
 * type of the {@code args} parameter of every constructor it generates. {@code ExtendedVerifier} then
 * moves the {@code @NamedParams} annotation of that parameter onto the type, and nothing ever removes
 * it, so the list grows by one entry per {@code @MapConstructor} lep class per compilation. Each entry
 * holds the expression graph of its own compilation, which pins the whole {@code CompilationUnit} -
 * parse trees, AST, asm writers, generated bytecode and the script class loader. Reproduced on groovy
 * 5.0.4 and 5.0.7.
 *
 * <p>The {@code LHMAP_TYPE} sibling, used for the special named argument case, was measured not to
 * accumulate on either version - it is reset here anyway, which costs nothing and keeps the guard
 * honest if that ever changes.
 *
 * <p>An accumulated list is not only a memory cost: {@code AsmClassGenerator} writes the whole list
 * into the bytecode of the next {@code @MapConstructor} class compiled, so one tenant's leftovers end
 * up in another tenant's classes - measured as 3 annotation instances on a clean node against 13 with
 * five foreign entries present. Classes that merely have a {@code Map} typed parameter were measured
 * to pick up nothing. Static type checking of named arguments was measured to stay correct either way.
 *
 * <p>Dropping the list costs a class its own {@code @NamedParams} only if the reset lands between the
 * verifier and the class generator of that class. What is lost then is the compile time named argument
 * check for {@code @CompileStatic} callers - an unknown or ill typed named argument surfaces as
 * {@code MissingPropertyException} or {@code GroovyCastException} at runtime instead. Valid calls, both
 * dynamic and statically compiled, were measured to behave identically.
 */
@Slf4j
// TODO FIXME remove this after all production tenants migrate from @MapConstructor annotations
public final class GroovyMapConstructorTypeAnnotations {

    private static final String TRANSFORMATION = "org.codehaus.groovy.transform.MapConstructorASTTransformation";
    private static final List<String> SHARED_NODE_FIELDS = List.of("MAP_TYPE", "LHMAP_TYPE");

    private static final List<ClassNode> SHARED_NODES = resolveSharedNodes();
    private static final Field TYPE_ANNOTATIONS = resolveTypeAnnotations();

    private GroovyMapConstructorTypeAnnotations() {
    }

    private static List<ClassNode> resolveSharedNodes() {
        List<ClassNode> nodes = new ArrayList<>();
        try {
            Class<?> transformation = Class.forName(TRANSFORMATION);
            for (String name : SHARED_NODE_FIELDS) {
                Field field = transformation.getDeclaredField(name);
                field.setAccessible(true);
                nodes.add((ClassNode) field.get(null));
            }
        } catch (ReflectiveOperationException | RuntimeException e) {
            log.warn("Cannot reach the shared {} nodes, they will not be cleared: {}", TRANSFORMATION, e.toString());
            return List.of();
        }
        return List.copyOf(nodes);
    }

    private static Field resolveTypeAnnotations() {
        try {
            Field field = ClassNode.class.getDeclaredField("typeAnnotations");
            field.setAccessible(true);
            return field;
        } catch (ReflectiveOperationException | RuntimeException e) {
            log.warn("Cannot reach ClassNode#typeAnnotations, it will not be cleared: {}", e.toString());
            return null;
        }
    }

    /** How many nodes are accumulated right now, across the shared types. Diagnostics only. */
    public static int accumulatedCount() {
        if (TYPE_ANNOTATIONS == null) {
            return 0;
        }
        int total = 0;
        for (ClassNode node : SHARED_NODES) {
            try {
                List<?> accumulated = (List<?>) TYPE_ANNOTATIONS.get(node);
                total += accumulated == null ? 0 : accumulated.size();
            } catch (ReflectiveOperationException | RuntimeException e) {
                log.warn("Failed to read accumulated @NamedParams nodes of {}: {}", node.getName(), e.toString());
            }
        }
        return total;
    }

    /**
     * Call at a compilation boundary. Lep classes are compiled lazily, on request threads, so a
     * compilation of another engine can be in flight: the reference is swapped rather than the list
     * cleared, which leaves a reader with either the whole previous list or an empty one, never a list
     * emptied underneath it. A class whose own annotation is dropped this way loses named argument
     * checking in the static type checker, nothing at runtime.
     */
    public static void clear() {
        if (TYPE_ANNOTATIONS == null) {
            return;
        }
        for (ClassNode node : SHARED_NODES) {
            try {
                List<?> accumulated = (List<?>) TYPE_ANNOTATIONS.get(node);
                if (accumulated != null && !accumulated.isEmpty()) {
                    log.info("Dropping {} @NamedParams nodes accumulated on the shared groovy {} type",
                        accumulated.size(), node.getName());
                    // back to the same empty list groovy starts from: addTypeAnnotation replaces it
                    // with a fresh ArrayList when it needs one again
                    TYPE_ANNOTATIONS.set(node, Collections.emptyList());
                }
            } catch (ReflectiveOperationException | RuntimeException e) {
                log.warn("Failed to clear accumulated @NamedParams nodes of {}: {}", node.getName(), e.toString());
            }
        }
    }
}
