package com.icthh.xm.commons.lep.groovy;

import groovy.lang.Closure;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Runtime support for code generated by {@code @XmMapConstructor} / {@code @XmToMap}.
 * All methods are null-safe: null input yields null output, never an exception.
 */
public final class XmMapSupport {

    private XmMapSupport() {
    }

    public static List<Object> mapList(Object value, Closure<?> itemMapper) {
        if (value == null) {
            return null;
        }
        List<Object> result = new ArrayList<>();
        for (Object item : (Collection<?>) value) {
            if (item != null) {
                result.add(itemMapper.call(item));
            }
        }
        return result;
    }

    public static Set<Object> mapSet(Object value, Closure<?> itemMapper) {
        if (value == null) {
            return null;
        }
        Set<Object> result = new LinkedHashSet<>();
        for (Object item : (Collection<?>) value) {
            if (item != null) {
                result.add(itemMapper.call(item));
            }
        }
        return result;
    }

    public static Map<Object, Object> mapMap(Object value, Closure<?> valueMapper) {
        if (value == null) {
            return null;
        }
        Map<Object, Object> result = new LinkedHashMap<>();
        for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
            Object entryValue = entry.getValue();
            result.put(entry.getKey(), entryValue == null ? null : valueMapper.call(entryValue));
        }
        return result;
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    public static Object toEnum(Class<?> enumType, Object value) {
        if (value == null) {
            return null;
        }
        try {
            return Enum.valueOf((Class<Enum>) enumType, value.toString());
        } catch (IllegalArgumentException e) {
            return null;
        }
    }

    public static Object safeEnum(Object value, Closure<?> mapper) {
        if (value == null) {
            return null;
        }
        try {
            return mapper.call(value);
        } catch (RuntimeException e) {
            return null;
        }
    }

    public static List<Object> toMapList(Object value) {
        if (value == null) {
            return null;
        }
        return new ArrayList<>((Collection<?>) value);
    }

    public static List<Object> toMapList(Object value, Closure<?> itemMapper) {
        return mapList(value, itemMapper);
    }

    public static Map<Object, Object> toMapMap(Object value, Closure<?> valueMapper) {
        return mapMap(value, valueMapper);
    }
}
